### ISSUE TITLE
Particles don't seem to render correctly

### ISSUE THREAD

**Issue by micsun-al** [playcanvas/webvr#4]
Here's the project:

https://playcanvas.com/project/393844/overview/webvr-test

The particles seem to show up on the left side correctly, but on the right side, they only seem to show up infrequently at a very low opacity.

![image](https://cloud.githubusercontent.com/assets/15949921/14722006/49973032-07be-11e6-8eb4-289b4ce2f563.png)
![image](https://cloud.githubusercontent.com/assets/15949921/14722216/538c13ae-07bf-11e6-9fb2-17af9b80985b.png)

I can't share a published build because for some reason builds on playcanv.as make it so the camera doesn't move when you move your phone around (can this be fixed on PlayCanvas's side?).  I think it's because of something like cross domain hosting or somethingsomething (pew pew shooting in the dark).

**Comment by willeastcott** [comment]
To share a working link to a published WebVR project, you need to change the link from the form:

https://playcanv.as/p/ABCD1232

To:

https://playcanv.as/e/p/ABCD1232

**Comment by micsun-al** [comment]
Oh neat, seems like there should be a link for that or something?  Cool info though, thanks!

Here's the published project:
https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/APLEVZYy/index.html

**Comment by willeastcott** [comment]
Closing because the [core engine now supports WebXR](https://developer.playcanvas.com/en/user-manual/xr/) and WebVR has been discontinued.
